### ISSUE TITLE
Refine Notebooks into Coherent Tutorial 

### ISSUE THREAD

**Issue by wip-abramson** [OpenMined/PyDentity#10]
## Where?
Additional notebooks need to be added. Demo should be converted to tutorial. Attempt similar to the PySyft style.

## What?
The tutorial should take someone with no understanding of SSI through to being able to use the aries-basic-controller library in there own projects.

**Comment by ramesht007** [comment]
hey, @wip-abramson I want to work on this issue 🙂

**Comment by wip-abramson** [comment]
Hey! 
That's great. So I am currently working on this in the feature/getting-started branch (sorry should have assigned myself). However, it would be awesome to have your help reviewing the material. If you could check out the tutorial and work through it, it would be really valuable.
Cheers :)

**Comment by ramesht007** [comment]
Thanks @wip-abramson

**Comment by wip-abramson** [comment]
Hey @ramesht007 I have merged this branch into master, but before I close this issue I would love to wait until you have been through the material (if you intent to do that).

Let me know, it would be super useful to get some outside review on these!

**Comment by ramesht007** [comment]
Sure @wip-abramson, thanks for asking, i would love to help you out.

**Comment by wip-abramson** [comment]
Great! This was the PR - https://github.com/OpenMined/PyDentity/pull/24

But you are best off running through the tutorials on master. I merged before the conference.

Thank you

**Comment by ramesht007** [comment]
ok thanks

**Comment by ramesht007** [comment]
I have read these notebooks and I would say they are sensational. 🙂
You are awesome. @wip-abramson

**Comment by wip-abramson** [comment]
Wow high praise! It was a team effort but thanks mate,  you are a star for going through them all. Are you interested to join the Identity team calls and work on other issues around this @ramesht007? You would be welcome :)

**Comment by ramesht007** [comment]
ya sure @wip-abramson 😀
