### ISSUE TITLE
Clearer posting of jupyter links

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyDentity#12]
## Description
running `./manage up` spams the terminal with a lot of information which, while useful, hides links to localhost needed to run the demos.

We should either reduce the amount of information being logged, or otherwise post the links in a more permanent and obvious position (through I mechanism I am yet to determine)

## Are you interested in working on this improvement yourself?
Sure

## Additional Context
N/A

**Comment by lohanspies** [comment]
Hey @TTitcombe - have a look at running this docker cmd after the notebook containers started. 
`docker exec -it aries-stagingnet_alice-notebook_1 jupyter notebook list`
Currently running servers:
http://0.0.0.0:8888/?token=1e426050323d9c83c445a5b2e8dbade5faa2abe03b437a48 :: /workspace

As you can see it will output the notebook URL for the container. Might be helpful.

**Comment by wip-abramson** [comment]
Yeah, we cannot easily reduce the logs because a lot of it is from the agent. But agree it would be nice have a better solution for this

**Comment by lohanspies** [comment]
This ticket can be closed with the implementation of this commit https://github.com/OpenMined/PyDentity/commit/9f84dc4cb95c9f21dadacb2aa858f7a7233dbcb9

**Comment by lohanspies** [comment]
Now you can just run `./scripts/get_URLS.sh` from the root folder to get all the notebook URLs with the correct port mapping

**Comment by wip-abramson** [comment]
The get_URLS.sh script is now in master
