### ISSUE TITLE
Create generic Dockerfile

### ISSUE THREAD

**Issue by TTitcombe** [OpenMined/PyDentity#13]
## Feature Description
Create a generic PyDentity Dockerfile that can be copied to any repository without breaking functionality.
This Dockerfile should have the basic controller installed.

## Is your feature request related to a problem?
The current Dockerfile in `libs/aries-basic-controller` installs the controller as a local pip install. Therefore, it must remain in the basic controller directory.

## What alternatives have you considered?
None

## Additional Context
Blocked by #11 (publish v0.1 to pypi)

**Comment by H4LL** [comment]
It may be good to scope this for the PyDentity sandpit which will contain every container which is involved in a demonstration. That way we can hone environments for specific demos also

**Comment by wip-abramson** [comment]
This is complete with the recent upgrade to aca-py 0.5.6. We now have a dockerfiles folder containing the generic dockerfiles used by all projects and tutorials rather than replicating Dockerfiles across many different folders.
