### ISSUE TITLE
Creation of AriesWorker for syft send/rcv messages over Aries channel.

### ISSUE THREAD

**Issue by H4LL** [OpenMined/PyDentity#2]
## Description

We'd like to extend the Baseworker class to use the basic messaging service in the Aries controller. We are beginning this below. The plan is to turn the binary into a string so that it can be communicated over the Aries Basic Message protocol. We're trying to send a syft tensor, x, over the channel. If the other side receives it, itll be able to interpret it with it's own Baseworker.

## How to Reproduce
1. Run through the README instructions
2. Once you get to the Syft experiment stage.

## what we need

We need AriesWorker send/rcv messages to be sent over the aries controller channel.

## System Information
 - Docker

**Comment by wip-abramson** [comment]
I think I want to close this @H4LL what do you think?

**Comment by wip-abramson** [comment]
I am closing this, we can reopen it later if needed.
