### ISSUE TITLE
Attachment Protocol

### ISSUE THREAD

**Issue by wip-abramson** [OpenMined/PyDentity#3]
## Feature Description
Enable attachments to be sent using a custom aries protocol over DIDComm. Extend the controller to handle this new protocol.

## Is your feature request related to a problem?
This is related to work exploring DIDComm for ML messages

**Comment by vineeth14** [comment]
I think this can be closed. The attachment protocol is done, right?

**Comment by wip-abramson** [comment]
Needed some work to be merged. All sorted now
