### ISSUE TITLE
Package notebook conflicts for: jupyter -> notebook notebook=5.7.8

### ISSUE THREAD

**Issue by frogman** [OpenMined/PyDentity#52]
## Description
Hi. 
During the ./manage start  testing of the aries-basic-controller I came accross an error with the package tools:
Step 6/12 : RUN conda install jupyter notebook=5.7.8
 ---> Running in 36c6eb8c464c
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package notebook conflicts for:
jupyter -> notebook
notebook=5.7.8

Package setuptools conflicts for:
python=3.8 -> pip -> setuptools
notebook=5.7.8 -> jinja2 -> setuptools

## How to Reproduce
1. Inside tutorials/aries-basic-controller#
2. /tutorials/manage start

## Expected Behavior
Docker build should went trough

## System Information
 - OS: Ubuntu 20.04
 - OS Version: focal
 - Language Version: Python 3.8.5
 - Docker Engine - Community Version:           20.10.1

**Comment by frogman** [comment]
Hi guys,

I have changed the notebook version because of the python 3.8 dependency:
/PyDentity/dockerfiles/controllers# ls Dockerfile.basiccontroller
changed the version 
#RUN conda install jupyter notebook=5.7.8
RUN conda install jupyter notebook=6.1.5

Installation went trough.

Will look further.

**Comment by wip-abramson** [comment]
Interesting, thanks for this. Probably we just need to make that change, I imagine 6.1.5 will work with an older version of python

**Comment by frogman** [comment]
Hi Will.
Yes I have tested it would work with older python versions, you can just make that small correction. 

Cheers. 

Zeljko
