### ISSUE TITLE
Refactor and Tidy Tutorials File Structure

### ISSUE THREAD

**Issue by wip-abramson** [OpenMined/PyDentity#61]
## What?
The tutorials are getting larger and the naming isn't always clear. I suggest we refactor as follows:

aries-basic-controller folder becomes 1. Learning Aries, ACA-Py and the Basic Controller
aries-staging-net becomes 2. Public ledger's and Mobile Wallet's

Open to suggestions on exact naming.

Additionally I suggest we consider refactoring the aries-basic-controller tutorial to have a subfolder or possibly multiple subfolders for advanced concepts. Mostly it frustrates me that Part 10 appears after Part 1 when you open the notebook, but I think this is a sensible refactor moving forwards.

Both Alice and Bob could have subfolder's for advanced concepts and also potentially for helper functions such as those described in issues #60  #59 #58.

For now revocation could move under the advanced concepts, and in the future tutorials on Mediation -  #41 and mutli wallets could go under here too.

There are also still a few floating notebooks that cover the basic API under a misc folder that I think should be removed.

## Why?
The refactor should not take too long, it is a renaming of the folder structure for our tutorials so they are more intuitive for students.

**Comment by morrieinmaas** [comment]
Can be extended by adding new tutorials for multitenant and mediation
