### ISSUE TITLE
Add Sub Wallet "Login" to AriesAgentController class

### ISSUE THREAD

**Issue by wip-abramson** [OpenMined/PyDentity#73]
## Description
Now we have the multitenant API we need to extend the AriesAgentController to be able to speak to the ACA-Py agent as that wallet. ACA-Py creates a JWT Bearer token for each subwallet that must be passed into the API.

We need to be able to set this token in our class. Either through the constructor, or just a getter or probably both.

## Are you interested in working on this improvement yourself?
- No but I think @morrieinmaas is going to take it on

## Additional Context
Add any other context or screenshots.

**Comment by morrieinmaas** [comment]
Will be closed by merge request for issue 61
