### ISSUE TITLE
No notebook named aries-stagingnet_issuer-notebook_1 for Tutorial 2

### ISSUE THREAD

**Issue by avinsit123** [OpenMined/PyDentity#76]
In `Tutorial 2. Public Ledgers and Mobile Wallets/` we are told to run `aries-stagingnet_issuer-notebook_1` to get the token. However, there are no such notebooks in the folder. Also, the first notebook says that Issuer and Verifier will be taken care of by the  `example/aries-stagingnet` docker environment but I am not able to find this environment anywhere. Am I looking in the wrong location or is this a documentation error?

**Comment by lohanspies** [comment]
Hi @avinsit123, to answer your first question regarding the token, the task is to run the cmd `docker logs aries-stagingnet_issuer-notebook_1` in the terminal to get the docker logs and extract the required token to access the `issuer` notebooks on http://localhost:8888/  and this cmd `docker logs aries-stagingnet_verifier-notebook_1` to get the token to access the `verifier` notebooks on http://localhost:8889/.

**Comment by lohanspies** [comment]
Can you please point me to the exact notebook where you seen the reference to the `example/aries-stagingnet` docker environment?

**Comment by wip-abramson** [comment]
FYI this is most likely because we recently renamed the folders e.g. aries-stagingnet now called 2. Mobile Agents and ... or something, meaning docker names will have changed. We should check all references to this, including in our readme which I think will be out of date

**Comment by morrieinmaas** [comment]
I see, I'll change the README accordingly to fit the new tutorial structure
